{% set name = "nbclient" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nbclient-{{ version }}.tar.gz
  sha256: 90b7fc6b810630db87a6d0c2250b1f0ab4cf4d3c27a299b0cde78a4ed3fd9193

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - jupyter-execute = nbclient.cli:main

requirements:
  host:
    - python
    - pip
    - hatchling >=1.10.0
  run:
    - python
    - jupyter_client >=6.1.12
    - jupyter_core >=4.12,!=5.0.*
    - nbformat >=5.1
    - traitlets >=5.4

test:
  imports:
    - nbclient
  requires:
    - pip
  commands:
    - pip check
    - jupyter-execute --help

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
  description: |
    NBClient is a tool for parameterizing and executing Jupyter Notebooks.
    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the jupyter_client
    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts to be run.
  dev_url: https://github.com/jupyter/nbclient
  doc_url: https://nbclient.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
