{% set name = "nbclient" %}
{% set version = "0.3.0" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e19f61896e0d2dae49e48ecc96ae60f6504e18aa25d165997953db867c45552c

build:
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - traitlets >=4.2
    - jupyter_client >=6.1.0
    - nbformat >=5.0
    - async_generator
    - nest-asyncio

test:
  imports:
    - nbclient

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
  description: |
    NBClient is a tool for parameterizing and executing Jupyter Notebooks.
    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the jupyter_client
    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts to be run.
  dev_url: https://github.com/jupyter/nbclient
  doc_url: https://nbclient.readthedocs.io
  doc_source_url: https://github.com/jupyter/nbclient/tree/master/docs

extra:
  recipe-maintainers:
    - davidbrochart
