{% set name = "nbclient" %}
{% set version = "0.5.11" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 751516992f34b58172bad54eef1e4bf7e4f4460d58e255ca1a4e5c9649476007

build:
  number: {{ build }}
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-execute = nbclient.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7
    - jupyter_client >=6.1.5
    - nbformat >=5.0
    - nest-asyncio
    - traitlets >=4.2

test:
  imports:
    - nbclient
  requires:
    - pip
  commands:
    - pip check
    - jupyter-execute --help

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
  description: |
    NBClient is a tool for parameterizing and executing Jupyter Notebooks.
    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the jupyter_client
    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts to be run.
  dev_url: https://github.com/jupyter/nbclient
  doc_url: https://nbclient.readthedocs.io
  doc_source_url: https://github.com/jupyter/nbclient/tree/master/docs

extra:
  recipe-maintainers:
    - davidbrochart
